version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /mnt/HC_Volume_104685938/itu-minitwit/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  cheep:
    image: jackhammers/minitwit:latest
    container_name: cheep
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://*:8081;http://*:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/cert/live/windysquirrels.dk/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/cert/live/windysquirrels.dk/privkey.pem
    volumes:
      - /etc/letsencrypt:/cert
    ports:
      - "443:8081"
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: